### ISSUE TITLE
Open Source GPL?

### ISSUE THREAD

**Issue by jau88** [ElectraJailbreak/unixtoolsrepo64#10]
Consider releasing the source code for the free programs as they required under the GPL license for distribution.

**Comment by coolstar** [comment]
Everything here is unmodified from their original upstream sources [see their tar files] (with the exception of dpkg/APT and anything at https://github.com/ElectraJailbreak/electra-patched)

For dpkg see: https://git.nito.tv/NitoTV/dpkg
For apt see: https://git.nito.tv/NitoTV/apt
