### ISSUE TITLE
all debs are zipped with ext xz  cannot unzip data.xz endless loop

### ISSUE THREAD

**Issue by pwned4ever** [ElectraJailbreak/unixtoolsrepo64#5]
is this normal and how the debs are going to be packed now or can you package the debs with the standard gz extension and or lzma ext at least so they can be unpacked ? will dpkg even work properly if the package can't be decompressed ? I had errors before because of the xz when I was trying to dpkg a deb file in earlier versions of electra

**Comment by coolstar** [comment]
dpkg and lzma on this repo should be packaged with gzip for an upgrade path. All other packages should be xz
